execution:
  transaction_costs:
    enabled: false
    mode: bps
    value: 0
    apply_on: notional
  slippage:
    enabled: false
    mode: bps
    value: 0
    reference_price: close
  liquidity:
    enabled: false
    max_participation: 0.1
    volume_source: bar_volume
  impact:
    enabled: false
    model: linear
    alpha: 0.0
    beta: 0.0
    decay: 0.0
    spread: 0.0
    average_daily_volume: 0
# sample data path for CLI backtest
data_path: data/backtest_sample.csv
