# Feature Engineering Configuration

# Price-based Features
price_features:
  - close_to_open
  - high_to_low
  - close_to_high
  - close_to_low
  - price_range

# Volume Features
volume_features:
  - volume_sma:
      periods: [5, 10, 20]
  - volume_ema:
      periods: [5, 10, 20]
  - volume_sma_ratios: [5, 10, 20]
  - volume_ema_ratios: [5, 10, 20]
  - on_balance_volume
  - volume_price_trend

# Volatility Features
volatility_features:
  - atr_periods: [14]
  - bollinger_bands:
      period: 20
      std_dev: 2
  - keltner_channels:
      periods: [20]
      atr_multiple: 2

# Custom Features
custom_features:
  - price_momentum:
      periods: [5, 10, 20]
  - volume_momentum:
      periods: [5, 10, 20]
  - mean_reversion:
      lookback: [5, 10, 20]
  - volatility_breakout:
      lookback: [20]
      threshold: 2.0

# Feature Combinations
feature_combinations:
  - cross_indicators:
      - ['sma_5', 'sma_20']
      - ['ema_5', 'ema_20']
      - ['close', 'sma_50']
  - ratio_indicators:
      - ['volume', 'volume_sma_5']
      - ['close', 'sma_20']
      - ['high', 'low']

# Sentiment Analysis (LLM-based)
# Configure LiteLLM provider/model and API key env var. Set `enabled: true` to
# generate a numeric sentiment score (-1 negative, 1 positive) for any text
# column named "text".
sentiment:
  enabled: false
  provider: openai        # e.g., openai, anthropic, huggingface, ollama
  model: gpt-3.5-turbo    # model name for the chosen provider
  api_key_env_var: OPENAI_API_KEY  # environment variable holding the API key
  extra: {}               # Additional LiteLLM params (e.g., base_url, temperature)

# Feature Selection
feature_selection:
  method: 'recursive'  # Options: recursive, lasso, random_forest
  n_features: 20
  scoring: 'f1'

# Feature Preprocessing
preprocessing:
  scaling:
    method: 'standard'  # Options: standard, minmax, robust
    target_range: [-1, 1]
  
  outliers:
    method: 'winsorize'  # Options: winsorize, clip
    limits: [0.01, 0.99]

# Feature Engineering Pipeline
pipeline:
  steps:
    - generate_technical_indicators
    - generate_volume_features
    - generate_custom_features
    - generate_sentiment
    - handle_missing_values
    - remove_outliers
    - scale_features
    - select_features
